import { PERMISSIONS_ACTIONS } from "./actions.constant";


export const ADMIN_TABLE = 'admin';

export const ADMIN_PERMISSIONS = {
    CREATE: `${ADMIN_TABLE}.${PERMISSIONS_ACTIONS.CREATE}`,
    READ: `${ADMIN_TABLE}.${PERMISSIONS_ACTIONS.READ}`,
    UPDATE: `${ADMIN_TABLE}.${PERMISSIONS_ACTIONS.UPDATE}`,
    DELETE: `${ADMIN_TABLE}.${PERMISSIONS_ACTIONS.DELETE}`,
    READ_OWN: `${ADMIN_TABLE}.${PERMISSIONS_ACTIONS.READ_OWN}`,
    ASSIGN: `${ADMIN_TABLE}.${PERMISSIONS_ACTIONS.ASSIGN}`,
}