import { PERMISSIONS_ACTIONS } from "./actions.constant";


export const COLLECTION_TABLE = 'collection';

export const COLLECTION_PERMISSIONS = {
    CREATE: `${COLLECTION_TABLE}.${PERMISSIONS_ACTIONS.CREATE}`,
    READ: `${COLLECTION_TABLE}.${PERMISSIONS_ACTIONS.READ}`,
    UPDATE: `${COLLECTION_TABLE}.${PERMISSIONS_ACTIONS.UPDATE}`,
    DELETE: `${COLLECTION_TABLE}.${PERMISSIONS_ACTIONS.DELETE}`,
    READ_OWN: `${COLLECTION_TABLE}.${PERMISSIONS_ACTIONS.READ_OWN}`,
    ASSIGN: `${COLLECTION_TABLE}.${PERMISSIONS_ACTIONS.ASSIGN}`,
}