import { PERMISSIONS_ACTIONS } from "./actions.constant";


export const ITEM_SPECIFIC_PERMISSION_TABLE = 'itemSpecificPermission';

export const ITEM_SPECIFIC_PERMISSION_PERMISSIONS = {
    CREATE: `${ITEM_SPECIFIC_PERMISSION_TABLE}.${PERMISSIONS_ACTIONS.CREATE}`,
    READ: `${ITEM_SPECIFIC_PERMISSION_TABLE}.${PERMISSIONS_ACTIONS.READ}`,
    UPDATE: `${ITEM_SPECIFIC_PERMISSION_TABLE}.${PERMISSIONS_ACTIONS.UPDATE}`,
    DELETE: `${ITEM_SPECIFIC_PERMISSION_TABLE}.${PERMISSIONS_ACTIONS.DELETE}`,
    READ_OWN: `${ITEM_SPECIFIC_PERMISSION_TABLE}.${PERMISSIONS_ACTIONS.READ_OWN}`,
    ASSIGN: `${ITEM_SPECIFIC_PERMISSION_TABLE}.${PERMISSIONS_ACTIONS.ASSIGN}`,

}