import { PERMISSIONS_ACTIONS } from "./actions.constant";


export const PERMISSION_TABLE = 'permission';

export const PERMISSION_PERMISSIONS = {
    CREATE: `${PERMISSION_TABLE}.${PERMISSIONS_ACTIONS.CREATE}`,
    READ: `${PERMISSION_TABLE}.${PERMISSIONS_ACTIONS.READ}`,
    UPDATE: `${PERMISSION_TABLE}.${PERMISSIONS_ACTIONS.UPDATE}`,
    DELETE: `${PERMISSION_TABLE}.${PERMISSIONS_ACTIONS.DELETE}`,
    READ_OWN: `${PERMISSION_TABLE}.${PERMISSIONS_ACTIONS.READ_OWN}`,
    ASSIGN: `${PERMISSION_TABLE}.${PERMISSIONS_ACTIONS.ASSIGN}`,
}