import { PERMISSIONS_ACTIONS } from "./actions.constant";


export const PLAN_TABLE = 'plan';

export const PLAN_PERMISSIONS = {
    CREATE: `${PLAN_TABLE}.${PERMISSIONS_ACTIONS.CREATE}`,
    READ: `${PLAN_TABLE}.${PERMISSIONS_ACTIONS.READ}`,
    UPDATE: `${PLAN_TABLE}.${PERMISSIONS_ACTIONS.UPDATE}`,
    DELETE: `${PLAN_TABLE}.${PERMISSIONS_ACTIONS.DELETE}`,
    READ_OWN: `${PLAN_TABLE}.${PERMISSIONS_ACTIONS.READ_OWN}`,
}