import { PERMISSIONS_ACTIONS } from "./actions.constant";


export const SCRAPPER_TABLE = 'scrapper';

export const SCRAPPER_PERMISSIONS = {
    CREATE: `${SCRAPPER_TABLE}.${PERMISSIONS_ACTIONS.CREATE}`,
    STATUS: `${SCRAPPER_TABLE}.${PERMISSIONS_ACTIONS.STATUS}`,
    READ: `${SCRAPPER_TABLE}.${PERMISSIONS_ACTIONS.READ}`,
    UPDATE: `${SCRAPPER_TABLE}.${PERMISSIONS_ACTIONS.UPDATE}`,
    DELETE: `${SCRAPPER_TABLE}.${PERMISSIONS_ACTIONS.DELETE}`,
    READ_OWN: `${SCRAPPER_TABLE}.${PERMISSIONS_ACTIONS.READ_OWN}`,
    ASSIGN: `${SCRAPPER_TABLE}.${PERMISSIONS_ACTIONS.ASSIGN}`,
}