import { PERMISSIONS_ACTIONS } from "./actions.constant";


export const TEMPLATE_TABLE = 'template';

export const TEMPLATE_PERMISSIONS = {
    CREATE: `${TEMPLATE_TABLE}.${PERMISSIONS_ACTIONS.CREATE}`,
    READ: `${TEMPLATE_TABLE}.${PERMISSIONS_ACTIONS.READ}`,
    UPDATE: `${TEMPLATE_TABLE}.${PERMISSIONS_ACTIONS.UPDATE}`,
    DELETE: `${TEMPLATE_TABLE}.${PERMISSIONS_ACTIONS.DELETE}`,
    READ_OWN: `${TEMPLATE_TABLE}.${PERMISSIONS_ACTIONS.READ_OWN}`,
    ASSIGN: `${TEMPLATE_TABLE}.${PERMISSIONS_ACTIONS.ASSIGN}`,
}