# Controls when the action will run.
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js and npm
      uses: actions/setup-node@v4
      with:
        node-version: 20.14.0
        cache: 'npm'

    - name: Install dependencies
      run: npm ci # `npm ci` Faster than `npm install` as it uses the lock file

    - name: Build project
      run: npm run build

    - name: Archive build artifacts
      run: tar -czf build-artifacts.tar.gz dist/
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: build-artifacts.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts

    - name: Deploy application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /var/www/admin_mobtwin
          rm -rf dist
          tar -xzf build-artifacts.tar.gz -C /var/www/admin_mobtwin
          rm build-artifacts.tar.gz
          cd ..
          docker compose up --build -d admin_mobtwin
